AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 CloudFormation Template

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Parameters:
          - EC2Name
          - EC2InstanceType
          - AMIId
          - KeyName
          - VPC
          - Subnet
          - AllocateEIP

    ParameterLabels:
      EC2Name:
        default: EC2 Instance Name
      EC2InstanceType:
        default: Instance Type
      AMIId:
        default: AMI Id
      KeyName:
        default: EC2 Key Pair Name
      AllocateEIP:
        default: Elastic IP


# Custom Variable for the environment
Parameters:
  EC2Name:
    Description: Name tag for EC2
    Type: String

  # Keypair should be manually created prior to create cloudformation stack(EC2 -> KeyPair)
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair

  EC2InstanceType:
    Description: Specify EC2 instance type
    Type: String

  VPC:
    Description: Specify VPC Id
    Type: AWS::EC2::VPC::Id

  Subnet:
    Description: Specify Subnet Id
    Type: AWS::EC2::Subnet::Id

  AMIId:
    Description: Specify AMI Id
    Type: AWS::EC2::Image::Id

  AllocateEIP:
    Description: Select "yes" if you want to assign EIP to an instance
    Type: String
    AllowedValues:
      - yes
      - no

Conditions:
  UseAllocateEIP: !Equals [!Ref AllocateEIP, yes]

Resources:

  # IAM roles assigned to EC2 instnaces
  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - ec2.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM

  # IAM Instance profile assigned to EC2 instnaces
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref IAMRole
    DependsOn: IAMRole

  # Security Group assigned to EC2 instnaces
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join ['-', [!Ref EC2Name, "sg"]]
      GroupDescription: !Join [' ', [!Ref EC2Name, "Instance", "Security Group"]]
      VpcId: !Ref VPC
      Tags:
        -
          Key: Name
          Value: !Join ['-', [!Ref EC2Name, "InstanceSecurityGroup"]]

  # Security Group Ingress Rule
  HTTPIngressRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref InstanceSecurityGroup
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      CidrIp: 0.0.0.0/0
    DependsOn:
      - InstanceSecurityGroup

  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMIId
      InstanceType: !Ref EC2InstanceType
      DisableApiTermination: false
      InstanceInitiatedShutdownBehavior: stop
      IamInstanceProfile: !Ref InstanceProfile
      Monitoring: false
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      SubnetId: !Ref Subnet
      Tags:
        -
          Key: Name
          Value: !Ref EC2Name
      UserData:
        Fn::Base64:
          !Sub |
              #!/bin/bash -xe
              sudo yum install -y httpd24
              echo "<html>Hello-World!!</html>" > /tmp/index.html
              sudo cp /tmp/index.html /var/www/html/index.html
              sudo chmod 755 /var/www/html/index.html
              sudo service httpd start
              sudo chkconfig httpd on
    DependsOn:
      - InstanceSecurityGroup
      - InstanceProfile
  
  ## Assign Elastic IP
  EIP:
    Type: AWS::EC2::EIP
    Condition: UseAllocateEIP

  ## Associate Elastic IP
  EIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Condition: UseAllocateEIP
    Properties:
      AllocationId: !GetAtt EIP.AllocationId
      InstanceId: !Ref Instance
    DependsOn:
      - EIP
      - Instance
